FROM r-base:3.4.0

RUN R -e 'source("https://bioconductor.org/biocLite.R"); biocLite("Biobase"); biocLite("viper"); biocLite("bcellViper")'
RUN R -e 'install.packages("optparse"); install.packages("ggplot2"); install.packages("reshape")'

WORKDIR /opt/viper
VOLUME /opt/viper

ADD run_viper.r /opt/viper/run_viper.r
ADD run_aracne2regulon.r /opt/viper/run_aracne2regulon.r
ADD viper_report.r /opt/viper/viper_report.r

ENV PATH="/opt/viper:${PATH}"
CMD ["Rscript", "/opt/viper/run_viper.r"]
